"""Change department to integer type

Revision ID: d579786640c8
Revises: 7ffccd7049bd
Create Date: 2025-11-04 17:22:03.933193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd579786640c8'
down_revision: Union[str, Sequence[str], None] = '7ffccd7049bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, set NULL for any existing string values
    op.execute("UPDATE users SET department = NULL WHERE department IS NOT NULL")
    
    # Now alter the column type with USING clause
    op.execute("ALTER TABLE users ALTER COLUMN department TYPE INTEGER USING department::integer")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
